-- JKI Taman Firdaus PostgreSQL backup
-- Generated by scripts/export-db-backup.ts
BEGIN;

TRUNCATE TABLE "Transaction", "Jemaat", "User" RESTART IDENTITY CASCADE;

INSERT INTO "User" ("id", "email", "passwordHash", "role", "openingBalance", "createdAt", "updatedAt") VALUES
(1, 'admin@gereja.id', 'admin123', 'ADMIN', 10000000, '2026-05-29T03:45:14.218Z', '2026-05-29T06:46:50.912Z');

INSERT INTO "Jemaat" ("id", "name", "address", "phone", "status", "initials", "createdAt", "updatedAt") VALUES
('JM-2022-145', 'Budi Setiawan', 'Jl. Sudirman Gg. Melati No. 45', '0811-2233-4455', 'TIDAK_AKTIF', 'BS', '2026-05-29T06:45:47.523Z', '2026-05-29T06:45:47.523Z'),
('JM-2023-001', 'Andreas Santoso', 'Jl. Kebon Jeruk No. 12, Jakarta Barat', '0812-3456-7890', 'AKTIF', 'AS', '2026-05-29T06:45:47.523Z', '2026-05-29T06:45:47.523Z'),
('JM-2023-002', 'Maria Lestari', 'Apartemen Park View Tower B Lt 10', '0813-9876-5432', 'AKTIF', 'ML', '2026-05-29T06:45:47.523Z', '2026-05-29T06:45:47.523Z'),
('JM-2023-015', 'Daniel Wijaya', 'Perum Citra Indah Blok C2/15', '0812-7788-9900', 'AKTIF', 'DW', '2026-05-29T06:45:47.523Z', '2026-05-29T06:45:47.523Z'),
('JM-2023-088', 'Ester Putri', 'Jl. Merdeka Baru No. 101, Tangerang', '0856-4433-2211', 'AKTIF', 'EP', '2026-05-29T06:45:47.523Z', '2026-05-29T06:45:47.523Z');

INSERT INTO "Transaction" ("id", "transactionDate", "type", "category", "amount", "note", "createdAt") VALUES
(18, '2023-10-24T00:00:00.000Z', 'PEMASUKAN', 'Persembahan Mingguan', 12500000, 'Kebaktian Umum I, II, dan III', '2026-05-29T06:45:47.534Z'),
(19, '2023-10-22T00:00:00.000Z', 'PENGELUARAN', 'Tagihan Listrik', -4200000, 'Pemakaian Gedung & Kantor (Sept)', '2026-05-29T06:45:47.534Z'),
(20, '2023-10-20T00:00:00.000Z', 'PEMASUKAN', 'Donasi Renovasi', 50000000, 'Donatur Anonim via Transfer', '2026-05-29T06:45:47.534Z'),
(21, '2023-10-18T00:00:00.000Z', 'PENGELUARAN', 'Gaji Staff', -28500000, 'Payroll 12 Karyawan Tetap', '2026-05-29T06:45:47.534Z'),
(22, '2023-10-15T00:00:00.000Z', 'PENGELUARAN', 'Pemeliharaan AC', -18500000, 'Service berkala 8 unit AC gedung', '2026-05-29T06:45:47.534Z'),
(23, '2026-05-29T00:00:00.000Z', 'PEMASUKAN', 'Perpuluhan MR A', 100000000, 'test', '2026-05-29T06:47:46.607Z');

SELECT setval(pg_get_serial_sequence('"User"', 'id'), 1, true);
SELECT setval(pg_get_serial_sequence('"Transaction"', 'id'), 23, true);

COMMIT;