import "dotenv/config";
import { writeFileSync } from "node:fs";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient, UserRole, JemaatStatus, TransactionType } from "../src/generated/prisma/client";

const connectionString = process.env.DATABASE_URL;
if (!connectionString) {
  throw new Error("DATABASE_URL is not set");
}

const adapter = new PrismaPg({ connectionString });
const prisma = new PrismaClient({ adapter });

const sqlString = (value: string) => `'${value.replace(/'/g, "''")}'`;
const sqlNullableString = (value: string | null | undefined) => {
  if (value == null) return "NULL";
  return sqlString(value);
};

const sqlDate = (value: Date) => sqlString(value.toISOString());

async function main() {
  const [users, jemaat, transactions] = await Promise.all([
    prisma.user.findMany({ orderBy: { id: "asc" } }),
    prisma.jemaat.findMany({ orderBy: { id: "asc" } }),
    prisma.transaction.findMany({ orderBy: { id: "asc" } }),
  ]);

  const lines: string[] = [];
  lines.push("-- JKI Taman Firdaus PostgreSQL backup");
  lines.push("-- Generated by scripts/export-db-backup.ts");
  lines.push("BEGIN;");
  lines.push("");
  lines.push("TRUNCATE TABLE \"Transaction\", \"Jemaat\", \"User\" RESTART IDENTITY CASCADE;");
  lines.push("");

  if (users.length > 0) {
    const values = users
      .map((u) => `(${u.id}, ${sqlString(u.email)}, ${sqlString(u.passwordHash)}, ${sqlString(UserRole[u.role])}, ${u.openingBalance}, ${sqlDate(u.createdAt)}, ${sqlDate(u.updatedAt)})`)
      .join(",\n");
    lines.push("INSERT INTO \"User\" (\"id\", \"email\", \"passwordHash\", \"role\", \"openingBalance\", \"createdAt\", \"updatedAt\") VALUES");
    lines.push(`${values};`);
    lines.push("");
  }

  if (jemaat.length > 0) {
    const values = jemaat
      .map((j) => `(${sqlString(j.id)}, ${sqlString(j.name)}, ${sqlString(j.address)}, ${sqlString(j.phone)}, ${sqlString(JemaatStatus[j.status])}, ${sqlString(j.initials)}, ${sqlDate(j.createdAt)}, ${sqlDate(j.updatedAt)})`)
      .join(",\n");
    lines.push("INSERT INTO \"Jemaat\" (\"id\", \"name\", \"address\", \"phone\", \"status\", \"initials\", \"createdAt\", \"updatedAt\") VALUES");
    lines.push(`${values};`);
    lines.push("");
  }

  if (transactions.length > 0) {
    const values = transactions
      .map((t) => `(${t.id}, ${sqlDate(t.transactionDate)}, ${sqlString(TransactionType[t.type])}, ${sqlString(t.category)}, ${t.amount}, ${sqlNullableString(t.note)}, ${sqlDate(t.createdAt)})`)
      .join(",\n");
    lines.push("INSERT INTO \"Transaction\" (\"id\", \"transactionDate\", \"type\", \"category\", \"amount\", \"note\", \"createdAt\") VALUES");
    lines.push(`${values};`);
    lines.push("");
  }

  const lastUserId = users.length > 0 ? users[users.length - 1].id : 0;
  const lastTransactionId = transactions.length > 0 ? transactions[transactions.length - 1].id : 0;

  lines.push(`SELECT setval(pg_get_serial_sequence('"User"', 'id'), ${lastUserId}, ${lastUserId > 0 ? "true" : "false"});`);
  lines.push(`SELECT setval(pg_get_serial_sequence('"Transaction"', 'id'), ${lastTransactionId}, ${lastTransactionId > 0 ? "true" : "false"});`);
  lines.push("");
  lines.push("COMMIT;");

  writeFileSync("database-backup/church_connect_latest.sql", lines.join("\n"), "utf8");
  console.log("Backup generated: database-backup/church_connect_latest.sql");
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (error) => {
    console.error(error);
    await prisma.$disconnect();
    process.exit(1);
  });
